/*
 * Blumatix.Capture.Webservice.Client.Selfhosted
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bludelta.Api;
using Bludelta.Model;
using Bludelta.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bludelta.Test.Model
{
    /// <summary>
    ///  Class for testing ContactResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContactResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContactResponse
        //private ContactResponse instance;

        public ContactResponseTests()
        {
            // TODO uncomment below to create an instance of ContactResponse
            //instance = new ContactResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContactResponse
        /// </summary>
        [Fact]
        public void ContactResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContactResponse
            //Assert.IsType<ContactResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'WebsiteUrl'
        /// </summary>
        [Fact]
        public void WebsiteUrlTest()
        {
            // TODO unit test for the property 'WebsiteUrl'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Fact]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }

    }

}
