/*
 * Blumatix.Capture.Webservice.Client.Selfhosted
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bludelta.Api;
using Bludelta.Model;
using Bludelta.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bludelta.Test.Model
{
    /// <summary>
    ///  Class for testing DetectionGroupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetectionGroupResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetectionGroupResponse
        //private DetectionGroupResponse instance;

        public DetectionGroupResponseTests()
        {
            // TODO uncomment below to create an instance of DetectionGroupResponse
            //instance = new DetectionGroupResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetectionGroupResponse
        /// </summary>
        [Fact]
        public void DetectionGroupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetectionGroupResponse
            //Assert.IsType<DetectionGroupResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TypeName'
        /// </summary>
        [Fact]
        public void TypeNameTest()
        {
            // TODO unit test for the property 'TypeName'
        }
        /// <summary>
        /// Test the property 'InvoiceDetailTypePredictions'
        /// </summary>
        [Fact]
        public void InvoiceDetailTypePredictionsTest()
        {
            // TODO unit test for the property 'InvoiceDetailTypePredictions'
        }

    }

}
