/*
 * Blumatix.Capture.Webservice.Client.Selfhosted
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bludelta.Api;
using Bludelta.Model;
using Bludelta.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bludelta.Test.Model
{
    /// <summary>
    ///  Class for testing DetectInvoiceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetectInvoiceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetectInvoiceRequest
        //private DetectInvoiceRequest instance;

        public DetectInvoiceRequestTests()
        {
            // TODO uncomment below to create an instance of DetectInvoiceRequest
            //instance = new DetectInvoiceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetectInvoiceRequest
        /// </summary>
        [Fact]
        public void DetectInvoiceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetectInvoiceRequest
            //Assert.IsType<DetectInvoiceRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
        /// <summary>
        /// Test the property 'Invoice'
        /// </summary>
        [Fact]
        public void InvoiceTest()
        {
            // TODO unit test for the property 'Invoice'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'PropertyStore'
        /// </summary>
        [Fact]
        public void PropertyStoreTest()
        {
            // TODO unit test for the property 'PropertyStore'
        }
        /// <summary>
        /// Test the property 'CreateResultPdf'
        /// </summary>
        [Fact]
        public void CreateResultPdfTest()
        {
            // TODO unit test for the property 'CreateResultPdf'
        }
        /// <summary>
        /// Test the property 'AddOcrResult'
        /// </summary>
        [Fact]
        public void AddOcrResultTest()
        {
            // TODO unit test for the property 'AddOcrResult'
        }
        /// <summary>
        /// Test the property 'AddDocumentText'
        /// </summary>
        [Fact]
        public void AddDocumentTextTest()
        {
            // TODO unit test for the property 'AddDocumentText'
        }
        /// <summary>
        /// Test the property 'Languages'
        /// </summary>
        [Fact]
        public void LanguagesTest()
        {
            // TODO unit test for the property 'Languages'
        }

    }

}
