/*
 * Blumatix.Capture.Webservice.Client.Selfhosted
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bludelta.Api;
using Bludelta.Model;
using Bludelta.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bludelta.Test.Model
{
    /// <summary>
    ///  Class for testing DetectInvoiceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetectInvoiceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetectInvoiceResponse
        //private DetectInvoiceResponse instance;

        public DetectInvoiceResponseTests()
        {
            // TODO uncomment below to create an instance of DetectInvoiceResponse
            //instance = new DetectInvoiceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetectInvoiceResponse
        /// </summary>
        [Fact]
        public void DetectInvoiceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetectInvoiceResponse
            //Assert.IsType<DetectInvoiceResponse>(instance);
        }


        /// <summary>
        /// Test the property 'DocumentResolution'
        /// </summary>
        [Fact]
        public void DocumentResolutionTest()
        {
            // TODO unit test for the property 'DocumentResolution'
        }
        /// <summary>
        /// Test the property 'DocumentFormat'
        /// </summary>
        [Fact]
        public void DocumentFormatTest()
        {
            // TODO unit test for the property 'DocumentFormat'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Countries'
        /// </summary>
        [Fact]
        public void CountriesTest()
        {
            // TODO unit test for the property 'Countries'
        }
        /// <summary>
        /// Test the property 'InvoiceDetailTypePredictions'
        /// </summary>
        [Fact]
        public void InvoiceDetailTypePredictionsTest()
        {
            // TODO unit test for the property 'InvoiceDetailTypePredictions'
        }
        /// <summary>
        /// Test the property 'PredictionGroups'
        /// </summary>
        [Fact]
        public void PredictionGroupsTest()
        {
            // TODO unit test for the property 'PredictionGroups'
        }
        /// <summary>
        /// Test the property 'LineItemTable'
        /// </summary>
        [Fact]
        public void LineItemTableTest()
        {
            // TODO unit test for the property 'LineItemTable'
        }
        /// <summary>
        /// Test the property 'Sender'
        /// </summary>
        [Fact]
        public void SenderTest()
        {
            // TODO unit test for the property 'Sender'
        }
        /// <summary>
        /// Test the property 'Receiver'
        /// </summary>
        [Fact]
        public void ReceiverTest()
        {
            // TODO unit test for the property 'Receiver'
        }
        /// <summary>
        /// Test the property 'Contacts'
        /// </summary>
        [Fact]
        public void ContactsTest()
        {
            // TODO unit test for the property 'Contacts'
        }
        /// <summary>
        /// Test the property 'FormattedResult'
        /// </summary>
        [Fact]
        public void FormattedResultTest()
        {
            // TODO unit test for the property 'FormattedResult'
        }
        /// <summary>
        /// Test the property 'IsQualityOk'
        /// </summary>
        [Fact]
        public void IsQualityOkTest()
        {
            // TODO unit test for the property 'IsQualityOk'
        }
        /// <summary>
        /// Test the property 'OcrWordQuality'
        /// </summary>
        [Fact]
        public void OcrWordQualityTest()
        {
            // TODO unit test for the property 'OcrWordQuality'
        }
        /// <summary>
        /// Test the property 'MeanCharacterConfidenceValue'
        /// </summary>
        [Fact]
        public void MeanCharacterConfidenceValueTest()
        {
            // TODO unit test for the property 'MeanCharacterConfidenceValue'
        }
        /// <summary>
        /// Test the property 'StdDevCharacterConfidenceValue'
        /// </summary>
        [Fact]
        public void StdDevCharacterConfidenceValueTest()
        {
            // TODO unit test for the property 'StdDevCharacterConfidenceValue'
        }
        /// <summary>
        /// Test the property 'MaxCharacterConfidenceValue'
        /// </summary>
        [Fact]
        public void MaxCharacterConfidenceValueTest()
        {
            // TODO unit test for the property 'MaxCharacterConfidenceValue'
        }
        /// <summary>
        /// Test the property 'OcrResult'
        /// </summary>
        [Fact]
        public void OcrResultTest()
        {
            // TODO unit test for the property 'OcrResult'
        }
        /// <summary>
        /// Test the property 'ResultPdf'
        /// </summary>
        [Fact]
        public void ResultPdfTest()
        {
            // TODO unit test for the property 'ResultPdf'
        }
        /// <summary>
        /// Test the property 'OcrPageImages'
        /// </summary>
        [Fact]
        public void OcrPageImagesTest()
        {
            // TODO unit test for the property 'OcrPageImages'
        }
        /// <summary>
        /// Test the property 'DocumentText'
        /// </summary>
        [Fact]
        public void DocumentTextTest()
        {
            // TODO unit test for the property 'DocumentText'
        }
        /// <summary>
        /// Test the property 'InvoiceState'
        /// </summary>
        [Fact]
        public void InvoiceStateTest()
        {
            // TODO unit test for the property 'InvoiceState'
        }
        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Fact]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }

    }

}
