/*
 * Blumatix.Capture.Webservice.Client.Selfhosted
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Bludelta.Api;
using Bludelta.Model;
using Bludelta.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Bludelta.Test.Model
{
    /// <summary>
    ///  Class for testing LineItemTableResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LineItemTableResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LineItemTableResponse
        //private LineItemTableResponse instance;

        public LineItemTableResponseTests()
        {
            // TODO uncomment below to create an instance of LineItemTableResponse
            //instance = new LineItemTableResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LineItemTableResponse
        /// </summary>
        [Fact]
        public void LineItemTableResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" LineItemTableResponse
            //Assert.IsType<LineItemTableResponse>(instance);
        }


        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Fact]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }

    }

}
