/*
 * Blumatix.Capture.Webservice.Client.Selfhosted
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Bludelta.Client.OpenAPIDateConverter;

namespace Bludelta.Model
{
    /// <summary>
    /// DetectionResponse
    /// </summary>
    [DataContract(Name = "DetectionResponse")]
    public partial class DetectionResponse : IEquatable<DetectionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DetectionResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DetectionResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DetectionResponse" /> class.
        /// </summary>
        /// <param name="type">Predicted invoice detail (required).</param>
        /// <param name="typeName">Predicted invoice detail (required).</param>
        /// <param name="text">The raw text.</param>
        /// <param name="value">Predicted value &lt;br&gt;&lt;br&gt;Formats:&lt;br&gt;&lt;ul&gt;&lt;li&gt;GrandTotalAmount: decimal separator &#39;.&#39;, no group separator, two decimal digits, e.g. 9.00, 2314.50, -12.99&lt;/li&gt;&lt;li&gt;NetAmount: decimal separator &#39;.&#39;, no group separator, two decimal digits, e.g. 9.00, 2314.50, -12.99&lt;/li&gt;&lt;li&gt;VatAmount: decimal separator &#39;.&#39;, no group separator, two decimal digits, e.g. 9.00, 2314.50, -12.99&lt;/li&gt;&lt;li&gt;VatRate: decimal separator &#39;.&#39;, no group separator, one decimal digits, e.g. 20.0, 19.0, 10.0&lt;/li&gt;&lt;li&gt;InvoiceDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;DeliveryDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;SenderOrderDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;ReceiverOrderDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;InvoiceId: string&lt;/li&gt;&lt;li&gt;InvoiceId: string&lt;/li&gt;&lt;li&gt;CustomerId: string&lt;/li&gt;&lt;li&gt;SenderOrderId: string&lt;/li&gt;&lt;li&gt;ReceiverOrderId: string&lt;/li&gt;&lt;li&gt;DocumentType: &#39;Invoice&#39; or &#39;CreditMemo&#39;&lt;/li&gt;&lt;li&gt;Ibans: string without blanks, comma separated&lt;/li&gt;&lt;li&gt;UstIds: string without blanks, comma separated&lt;/li&gt;&lt;/ul&gt; (required).</param>
        /// <param name="score">Scored probability. Value between zero and one. (required).</param>
        /// <param name="x">X-Position according to the document resolution (required).</param>
        /// <param name="y">Y-Position according to the document resolution (required).</param>
        /// <param name="width">Width according to the document resolution (required).</param>
        /// <param name="height">Height according to the document resolution (required).</param>
        /// <param name="confidence">Describes the confidence that this invoice detail can be auto-processed without human validation. (-1 &#x3D; unknown, 0 &#x3D; validate manually, 1 &#x3D; autoprocess).</param>
        public DetectionResponse(long type = default(long), string typeName = default(string), string text = default(string), string value = default(string), double score = default(double), int x = default(int), int y = default(int), int width = default(int), int height = default(int), float confidence = default(float))
        {
            this.Type = type;
            // to ensure "typeName" is required (not null)
            if (typeName == null) {
                throw new ArgumentNullException("typeName is a required property for DetectionResponse and cannot be null");
            }
            this.TypeName = typeName;
            // to ensure "value" is required (not null)
            if (value == null) {
                throw new ArgumentNullException("value is a required property for DetectionResponse and cannot be null");
            }
            this.Value = value;
            this.Score = score;
            this.X = x;
            this.Y = y;
            this.Width = width;
            this.Height = height;
            this.Text = text;
            this.Confidence = confidence;
        }

        /// <summary>
        /// Predicted invoice detail
        /// </summary>
        /// <value>Predicted invoice detail</value>
        [DataMember(Name = "Type", IsRequired = true, EmitDefaultValue = false)]
        public long Type { get; set; }

        /// <summary>
        /// Predicted invoice detail
        /// </summary>
        /// <value>Predicted invoice detail</value>
        [DataMember(Name = "TypeName", IsRequired = true, EmitDefaultValue = false)]
        public string TypeName { get; set; }

        /// <summary>
        /// The raw text
        /// </summary>
        /// <value>The raw text</value>
        [DataMember(Name = "Text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Predicted value &lt;br&gt;&lt;br&gt;Formats:&lt;br&gt;&lt;ul&gt;&lt;li&gt;GrandTotalAmount: decimal separator &#39;.&#39;, no group separator, two decimal digits, e.g. 9.00, 2314.50, -12.99&lt;/li&gt;&lt;li&gt;NetAmount: decimal separator &#39;.&#39;, no group separator, two decimal digits, e.g. 9.00, 2314.50, -12.99&lt;/li&gt;&lt;li&gt;VatAmount: decimal separator &#39;.&#39;, no group separator, two decimal digits, e.g. 9.00, 2314.50, -12.99&lt;/li&gt;&lt;li&gt;VatRate: decimal separator &#39;.&#39;, no group separator, one decimal digits, e.g. 20.0, 19.0, 10.0&lt;/li&gt;&lt;li&gt;InvoiceDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;DeliveryDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;SenderOrderDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;ReceiverOrderDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;InvoiceId: string&lt;/li&gt;&lt;li&gt;InvoiceId: string&lt;/li&gt;&lt;li&gt;CustomerId: string&lt;/li&gt;&lt;li&gt;SenderOrderId: string&lt;/li&gt;&lt;li&gt;ReceiverOrderId: string&lt;/li&gt;&lt;li&gt;DocumentType: &#39;Invoice&#39; or &#39;CreditMemo&#39;&lt;/li&gt;&lt;li&gt;Ibans: string without blanks, comma separated&lt;/li&gt;&lt;li&gt;UstIds: string without blanks, comma separated&lt;/li&gt;&lt;/ul&gt;
        /// </summary>
        /// <value>Predicted value &lt;br&gt;&lt;br&gt;Formats:&lt;br&gt;&lt;ul&gt;&lt;li&gt;GrandTotalAmount: decimal separator &#39;.&#39;, no group separator, two decimal digits, e.g. 9.00, 2314.50, -12.99&lt;/li&gt;&lt;li&gt;NetAmount: decimal separator &#39;.&#39;, no group separator, two decimal digits, e.g. 9.00, 2314.50, -12.99&lt;/li&gt;&lt;li&gt;VatAmount: decimal separator &#39;.&#39;, no group separator, two decimal digits, e.g. 9.00, 2314.50, -12.99&lt;/li&gt;&lt;li&gt;VatRate: decimal separator &#39;.&#39;, no group separator, one decimal digits, e.g. 20.0, 19.0, 10.0&lt;/li&gt;&lt;li&gt;InvoiceDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;DeliveryDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;SenderOrderDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;ReceiverOrderDate: YYYY-MM-DD (ISO 8601)&lt;/li&gt;&lt;li&gt;InvoiceId: string&lt;/li&gt;&lt;li&gt;InvoiceId: string&lt;/li&gt;&lt;li&gt;CustomerId: string&lt;/li&gt;&lt;li&gt;SenderOrderId: string&lt;/li&gt;&lt;li&gt;ReceiverOrderId: string&lt;/li&gt;&lt;li&gt;DocumentType: &#39;Invoice&#39; or &#39;CreditMemo&#39;&lt;/li&gt;&lt;li&gt;Ibans: string without blanks, comma separated&lt;/li&gt;&lt;li&gt;UstIds: string without blanks, comma separated&lt;/li&gt;&lt;/ul&gt;</value>
        [DataMember(Name = "Value", IsRequired = true, EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Scored probability. Value between zero and one.
        /// </summary>
        /// <value>Scored probability. Value between zero and one.</value>
        [DataMember(Name = "Score", IsRequired = true, EmitDefaultValue = false)]
        public double Score { get; set; }

        /// <summary>
        /// X-Position according to the document resolution
        /// </summary>
        /// <value>X-Position according to the document resolution</value>
        [DataMember(Name = "X", IsRequired = true, EmitDefaultValue = false)]
        public int X { get; set; }

        /// <summary>
        /// Y-Position according to the document resolution
        /// </summary>
        /// <value>Y-Position according to the document resolution</value>
        [DataMember(Name = "Y", IsRequired = true, EmitDefaultValue = false)]
        public int Y { get; set; }

        /// <summary>
        /// Width according to the document resolution
        /// </summary>
        /// <value>Width according to the document resolution</value>
        [DataMember(Name = "Width", IsRequired = true, EmitDefaultValue = false)]
        public int Width { get; set; }

        /// <summary>
        /// Height according to the document resolution
        /// </summary>
        /// <value>Height according to the document resolution</value>
        [DataMember(Name = "Height", IsRequired = true, EmitDefaultValue = false)]
        public int Height { get; set; }

        /// <summary>
        /// Describes the confidence that this invoice detail can be auto-processed without human validation. (-1 &#x3D; unknown, 0 &#x3D; validate manually, 1 &#x3D; autoprocess)
        /// </summary>
        /// <value>Describes the confidence that this invoice detail can be auto-processed without human validation. (-1 &#x3D; unknown, 0 &#x3D; validate manually, 1 &#x3D; autoprocess)</value>
        [DataMember(Name = "Confidence", EmitDefaultValue = false)]
        public float Confidence { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DetectionResponse {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  TypeName: ").Append(TypeName).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DetectionResponse);
        }

        /// <summary>
        /// Returns true if DetectionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of DetectionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DetectionResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                ) && 
                (
                    this.TypeName == input.TypeName ||
                    (this.TypeName != null &&
                    this.TypeName.Equals(input.TypeName))
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.Score == input.Score ||
                    this.Score.Equals(input.Score)
                ) && 
                (
                    this.X == input.X ||
                    this.X.Equals(input.X)
                ) && 
                (
                    this.Y == input.Y ||
                    this.Y.Equals(input.Y)
                ) && 
                (
                    this.Width == input.Width ||
                    this.Width.Equals(input.Width)
                ) && 
                (
                    this.Height == input.Height ||
                    this.Height.Equals(input.Height)
                ) && 
                (
                    this.Confidence == input.Confidence ||
                    this.Confidence.Equals(input.Confidence)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.TypeName != null)
                    hashCode = hashCode * 59 + this.TypeName.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                hashCode = hashCode * 59 + this.Score.GetHashCode();
                hashCode = hashCode * 59 + this.X.GetHashCode();
                hashCode = hashCode * 59 + this.Y.GetHashCode();
                hashCode = hashCode * 59 + this.Width.GetHashCode();
                hashCode = hashCode * 59 + this.Height.GetHashCode();
                hashCode = hashCode * 59 + this.Confidence.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
