/*
 * Blumatix.Capture.Webservice.Client.Selfhosted
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Bludelta.Client;
using Bludelta.Api;
// uncomment below to import models
//using Bludelta.Model;

namespace Bludelta.Test.Api
{
    /// <summary>
    ///  Class for testing InvoicedetailApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InvoicedetailApiTests : IDisposable
    {
        private InvoicedetailApi instance;

        public InvoicedetailApiTests()
        {
            instance = new InvoicedetailApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoicedetailApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InvoicedetailApi
            //Assert.IsType<InvoicedetailApi>(instance);
        }

        /// <summary>
        /// Test DetectInvoiceRequestdetectPost
        /// </summary>
        [Fact]
        public void DetectInvoiceRequestdetectPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accept = null;
            //long? filter = null;
            //string invoice = null;
            //int? format = null;
            //bool? createResultPdf = null;
            //bool? addOcrResult = null;
            //bool? addOcrPageImages = null;
            //bool? addDocumentText = null;
            //string languages = null;
            //var response = instance.DetectInvoiceRequestdetectPost(accept, filter, invoice, format, createResultPdf, addOcrResult, addOcrPageImages, addDocumentText, languages);
            //Assert.IsType<DetectInvoiceResponse>(response);
        }
    }
}
